# Generated by Django 4.2.30 on 2026-10-08 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cellule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_cellule", models.CharField(max_length=30, unique=True)),
                ("pavillon", models.CharField(max_length=50)),
                ("bloc", models.CharField(max_length=50)),
                ("capacite_max", models.PositiveIntegerField(default=10)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("pleine", "Pleine"),
                            ("maintenance", "En maintenance"),
                            ("isolement", "Cellule d'isolement"),
                        ],
                        default="disponible",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cellules",
                "ordering": ["pavillon", "bloc", "code_cellule"],
            },
        ),
        migrations.CreateModel(
            name="Detenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricule", models.CharField(max_length=50, unique=True)),
                ("nom", models.CharField(max_length=100)),
                ("postnom", models.CharField(blank=True, max_length=100, null=True)),
                ("prenom", models.CharField(max_length=100)),
                ("date_naissance", models.DateField()),
                ("lieu_naissance", models.CharField(max_length=100)),
                (
                    "genre",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin")],
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "nationalite",
                    models.CharField(default="Congolaise (RDC)", max_length=100),
                ),
                (
                    "etat_civil",
                    models.CharField(
                        choices=[
                            ("celibataire", "Célibataire"),
                            ("marie", "Marié(e)"),
                            ("divorce", "Divorcé(e)"),
                            ("veuf", "Veuf/Veuve"),
                        ],
                        default="celibataire",
                        max_length=20,
                    ),
                ),
                ("adresse", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "photo",
                    models.CharField(default="default_detenu.png", max_length=255),
                ),
                (
                    "statut_judiciaire",
                    models.CharField(
                        choices=[
                            ("prevenu", "Prévenu"),
                            ("condamne", "Condamné"),
                            ("transfere", "Transféré"),
                            ("libere", "Libéré"),
                            ("decede", "Décédé"),
                            ("archive", "Archivé"),
                        ],
                        default="prevenu",
                        max_length=20,
                    ),
                ),
                (
                    "niveau_dangerosite",
                    models.CharField(
                        choices=[
                            ("faible", "Faible"),
                            ("moyen", "Moyen"),
                            ("eleve", "Élevé"),
                            ("critique", "Critique"),
                        ],
                        default="faible",
                        max_length=20,
                    ),
                ),
                ("date_ecrou", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_liberation_prevue", models.DateField(blank=True, null=True)),
                (
                    "date_liberation_effective",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("motif_inculpation", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cellule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detenus",
                        to="prison.cellule",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detenus_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "detenus",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Visite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_visiteur", models.CharField(max_length=100)),
                ("prenom_visiteur", models.CharField(max_length=100)),
                ("lien_parente", models.CharField(max_length=50)),
                (
                    "type_piece_identite",
                    models.CharField(default="Carte d'Électeur", max_length=50),
                ),
                ("numero_piece", models.CharField(max_length=100)),
                ("telephone", models.CharField(blank=True, max_length=30, null=True)),
                ("date_visite", models.DateField()),
                ("heure_debut", models.TimeField()),
                ("heure_fin", models.TimeField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("demande", "En attente"),
                            ("autorisee", "Autorisée"),
                            ("refusee", "Refusée"),
                            ("terminee", "Terminée"),
                            ("annulee", "Annulée"),
                        ],
                        default="autorisee",
                        max_length=20,
                    ),
                ),
                (
                    "objet_visite",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("effets_apportes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "detenu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visites",
                        to="prison.detenu",
                    ),
                ),
                (
                    "enregistre_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visites_enregistrees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "visites",
                "ordering": ["-date_visite", "-heure_debut"],
            },
        ),
        migrations.CreateModel(
            name="Transfert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etablissement_provenance",
                    models.CharField(
                        default="Prison Centrale de Makala", max_length=150
                    ),
                ),
                ("etablissement_destination", models.CharField(max_length=150)),
                ("motif_transfert", models.TextField()),
                ("date_transfert", models.DateField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("en_cours", "En cours d'exécution"),
                            ("effectue", "Effectué"),
                            ("annule", "Annulé"),
                        ],
                        default="planifie",
                        max_length=20,
                    ),
                ),
                (
                    "escorte_agents",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "autorise_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transferts_autorises",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "detenu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transferts",
                        to="prison.detenu",
                    ),
                ),
            ],
            options={
                "db_table": "transferts",
                "ordering": ["-date_transfert", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Jugement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tribunal", models.CharField(max_length=150)),
                ("numero_dossier", models.CharField(max_length=100)),
                ("date_jugement", models.DateField()),
                (
                    "type_decision",
                    models.CharField(
                        choices=[
                            ("condamnation", "Condamnation"),
                            ("acquittement", "Acquittement"),
                            ("renvoi", "Renvoi"),
                            ("liberation_conditionnelle", "Libération conditionnelle"),
                        ],
                        max_length=30,
                    ),
                ),
                ("peine_ans", models.PositiveIntegerField(default=0)),
                ("peine_mois", models.PositiveIntegerField(default=0)),
                (
                    "peine_amende",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("resume_verdict", models.TextField()),
                (
                    "document_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("juge_nom", models.CharField(blank=True, max_length=150, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jugements_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "detenu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jugements",
                        to="prison.detenu",
                    ),
                ),
            ],
            options={
                "db_table": "jugements",
                "ordering": ["-date_jugement", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DocumentJudiciaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=150)),
                (
                    "type_doc",
                    models.CharField(
                        choices=[
                            ("mandat_depot", "Mandat de Dépôt"),
                            ("acte_accusation", "Acte d'Accusation"),
                            ("fiche_medicale", "Fiche Médicale"),
                            ("jugement", "Copie du Jugement"),
                            ("ordre_liberation", "Ordre de Libération"),
                            ("autre", "Autre Document"),
                        ],
                        max_length=30,
                    ),
                ),
                ("fichier_path", models.CharField(max_length=255)),
                ("taille_ko", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "detenu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="prison.detenu",
                    ),
                ),
                (
                    "uploade_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents_uploades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "documents",
                "ordering": ["-created_at"],
            },
        ),
    ]
